GET http://localhost:8001/1qaz
Accept: application/json

###

POST http://localhost:8001/get
Accept: application/json
Content-Type: application/json

{
    "id": "69a78e85-5dfa-40fe-9bb4-b4012f37f774",
    "password": "fweItbGHfE/RcLju1pQ0e3JrkG+4zBMmVow6r1DpRlQ="
}

###

POST http://localhost:8001/create
Accept: application/json
Content-Type: application/json

{
    "payload": "fidelio",
    "password": "kubrick",
    "lifetime": "Lifetime1d"
}