GET http://localhost:8001/Secrets
Accept: application/json

###

POST http://localhost:8001/Get
Accept: application/json
Content-Type: application/json

{
    "id": "3defab27-f441-4fae-b4aa-3afd2529f3e5",
    "password": ""
}

###

POST http://localhost:8001/CreateSecret
Accept: application/json
Content-Type: application/json

{
    "payload": "fidelio"
}